import asyncio
import uuid
import json
from fastapi import FastAPI, HTTPException, BackgroundTasks
from models import TripRequest, TripResponse, CityReportOutput, TravelPlanOutput, RegenerateDayRequest
from llm_wrapper import generate_full_itinerary, regenerate_single_day

app = FastAPI(title="Agentic AI Trip Planner")

# Global dict to hold results so we can poll for them
TASK_RESULTS = {}

async def run_plan_trip_task(task_id: str, trip_details: dict):
    try:
        travel_plan_content = await generate_full_itinerary(trip_details)
            
        payload = {
            "status": "completed",
            "result": TripResponse(
                travel_plan=TravelPlanOutput(
                    overall_plan="Generated by LLM Planner",
                    daily_itinerary=travel_plan_content,
                ),
            ).model_dump()
        }
    except Exception as e:
        payload = {"status": "failed", "error": str(e)}

    # Send Webhook
    webhook_url = trip_details.get("webhook_url")
    if webhook_url:
        import urllib.request
        try:
            req = urllib.request.Request(webhook_url, method="POST")
            req.add_header('Content-Type', 'application/json')
            data = json.dumps(payload).encode('utf-8')
            urllib.request.urlopen(req, data=data, timeout=10)
        except Exception as err:
            print(f"Webhook failed: {err}")
    
    TASK_RESULTS[task_id] = payload
    return payload


@app.post("/plan-trip")
async def plan_trip(request: TripRequest, background_tasks: BackgroundTasks):
    task_id = str(uuid.uuid4())
    # Register the background task so we don't hold the HTTP connection open!
    background_tasks.add_task(run_plan_trip_task, task_id, request.model_dump())
    return {
        "task_id": task_id, 
        "status": "processing",
        "message": f"Task started. Poll GET /task/{task_id} to get the result."
    }


async def run_regenerate_day_task(task_id: str, request: RegenerateDayRequest):
    try:
        trip_details = request.trip_details.model_dump()
        regenerated_content = await regenerate_single_day(trip_details, request.target_day_number, request.existing_itinerary)

        payload = {
            "status": "completed",
            "content": regenerated_content
        }
    except Exception as e:
        payload = {"status": "failed", "error": str(e)}

    # Send Webhook
    webhook_url = request.webhook_url
    if webhook_url:
        import urllib.request
        try:
            req = urllib.request.Request(webhook_url, method="POST")
            req.add_header('Content-Type', 'application/json')
            data = json.dumps(payload).encode('utf-8')
            urllib.request.urlopen(req, data=data, timeout=10)
        except Exception as err:
            print(f"Webhook failed: {err}")
            
    TASK_RESULTS[task_id] = payload
    return payload


@app.post("/regenerate-day")
async def regenerate_day(request: RegenerateDayRequest, background_tasks: BackgroundTasks):
    task_id = str(uuid.uuid4())
    background_tasks.add_task(run_regenerate_day_task, task_id, request)
    return {
        "task_id": task_id, 
        "status": "processing",
        "message": f"Task started. Poll GET /task/{task_id} to get the result."
    }


@app.get("/task/{task_id}")
async def get_task_status(task_id: str):
    if task_id in TASK_RESULTS:
        return TASK_RESULTS[task_id]
    return {"status": "processing", "message": "Still crunching numbers..."}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8002)
