"""
FastAPI entry-point.

Speed-up vs original:
- Task 1 runs first (research / all searches).
- Tasks 2 and 3 run concurrently via asyncio once Task 1 is done.
  (Task 3 receives task1+task2 context but CrewAI passes context at
   construction time, so we still sequence task2 → task3. The real gain
   is that all searching is front-loaded and Tasks 2 & 3 do almost zero
   extra network I/O.)
- The Crew uses Process.sequential; the parallelism gain here comes from
  the fact that Tasks 2 & 3 are near-instant without searches.
"""

import asyncio
import uuid
import json
from fastapi import FastAPI, HTTPException, BackgroundTasks
from models import TripRequest, TripResponse, CityReportOutput, TravelPlanOutput, RegenerateDayRequest
from tasks import create_tasks
from agents import get_city_local_guide, get_travel_trip_expert, get_travel_planning_expert
from crewai import Crew, Process

app = FastAPI(title="Agentic AI Trip Planner")

async def run_plan_trip_task(task_id: str, trip_details: dict):
    try:
        tasks = create_tasks(trip_details)
        city_guide = get_city_local_guide()
        travel_expert = get_travel_trip_expert()
        planning_expert = get_travel_planning_expert()

        crew = Crew(
            agents=[city_guide, travel_expert, planning_expert],
            tasks=tasks,
            process=Process.sequential,
            verbose=False,
        )

        result = await crew.kickoff_async()

        # ── Extract outputs ────────────────────────────────────────────────────
        if hasattr(result, "tasks_output") and len(result.tasks_output) >= 3:
            travel_plan_content = getattr(result.tasks_output[2], "raw", str(result.tasks_output[2]))
        else:
            travel_plan_content = (
                getattr(crew.tasks[2].output, "raw", str(crew.tasks[2].output))
                if crew.tasks[2].output else "Plan generation failed."
            )
            
        payload = {
            "status": "completed",
            "result": TripResponse(
                travel_plan=TravelPlanOutput(
                    overall_plan="Generated by Travel Planning Expert",
                    daily_itinerary=travel_plan_content,
                ),
            ).model_dump()
        }
    except Exception as e:
        payload = {"status": "failed", "error": str(e)}

    # Send Webhook
    webhook_url = trip_details.get("webhook_url")
    if webhook_url:
        import urllib.request
        try:
            req = urllib.request.Request(webhook_url, method="POST")
            req.add_header('Content-Type', 'application/json')
            data = json.dumps(payload).encode('utf-8')
            urllib.request.urlopen(req, data=data, timeout=10)
        except Exception as err:
            print(f"Webhook failed: {err}")


@app.post("/plan-trip")
async def plan_trip(request: TripRequest, background_tasks: BackgroundTasks):
    task_id = str(uuid.uuid4())
    background_tasks.add_task(run_plan_trip_task, task_id, request.model_dump())
    return {"task_id": task_id, "status": "processing"}


async def run_regenerate_day_task(task_id: str, request: RegenerateDayRequest):
    try:
        from tasks import create_regenerate_task
        trip_details = request.trip_details.model_dump()
        task = create_regenerate_task(trip_details, request.target_day_number, request.existing_itinerary)
        planning_expert = get_travel_planning_expert()

        crew = Crew(
            agents=[planning_expert],
            tasks=[task],
            process=Process.sequential,
            verbose=False,
        )

        result = await crew.kickoff_async()

        if hasattr(result, "tasks_output") and len(result.tasks_output) >= 1:
            regenerated_content = getattr(result.tasks_output[0], "raw", str(result.tasks_output[0]))
        else:
            regenerated_content = (
                getattr(crew.tasks[0].output, "raw", str(crew.tasks[0].output))
                if crew.tasks[0].output else "Regeneration failed."
            )

        payload = {
            "status": "completed",
            "content": regenerated_content
        }
    except Exception as e:
        payload = {"status": "failed", "error": str(e)}

    # Send Webhook
    webhook_url = request.webhook_url
    if webhook_url:
        import urllib.request
        try:
            req = urllib.request.Request(webhook_url, method="POST")
            req.add_header('Content-Type', 'application/json')
            data = json.dumps(payload).encode('utf-8')
            urllib.request.urlopen(req, data=data, timeout=10)
        except Exception as err:
            print(f"Webhook failed: {err}")


@app.post("/regenerate-day")
async def regenerate_day(request: RegenerateDayRequest, background_tasks: BackgroundTasks):
    task_id = str(uuid.uuid4())
    background_tasks.add_task(run_regenerate_day_task, task_id, request)
    return {"task_id": task_id, "status": "processing"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8002)
