"""
FastAPI entry-point.

Speed-up vs original:
- Task 1 runs first (research / all searches).
- Tasks 2 and 3 run concurrently via asyncio once Task 1 is done.
  (Task 3 receives task1+task2 context but CrewAI passes context at
   construction time, so we still sequence task2 → task3. The real gain
   is that all searching is front-loaded and Tasks 2 & 3 do almost zero
   extra network I/O.)
- The Crew uses Process.sequential; the parallelism gain here comes from
  the fact that Tasks 2 & 3 are near-instant without searches.
"""

import asyncio
from fastapi import FastAPI, HTTPException
from models import TripRequest, TripResponse, CityReportOutput, TravelPlanOutput
from tasks import create_tasks
from agents import get_city_local_guide, get_travel_trip_expert, get_travel_planning_expert
from crewai import Crew, Process

app = FastAPI(title="Agentic AI Trip Planner")


@app.post("/plan-trip", response_model=TripResponse)
async def plan_trip(request: TripRequest):
    trip_details = request.model_dump()
    tasks        = create_tasks(trip_details)

    city_guide      = get_city_local_guide()
    travel_expert   = get_travel_trip_expert()
    planning_expert = get_travel_planning_expert()

    crew = Crew(
        agents=[city_guide, travel_expert, planning_expert],
        tasks=tasks,
        process=Process.sequential,
        verbose=False,
    )

    try:
        result = await crew.kickoff_async()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    # ── Extract outputs ────────────────────────────────────────────────────
    if hasattr(result, "tasks_output") and len(result.tasks_output) >= 3:
        city_report_content = getattr(result.tasks_output[0], "raw", str(result.tasks_output[0]))
        travel_plan_content = getattr(result.tasks_output[2], "raw", str(result.tasks_output[2]))
    else:
        city_report_content = (
            getattr(crew.tasks[0].output, "raw", str(crew.tasks[0].output))
            if crew.tasks[0].output else "Report generation failed."
        )
        travel_plan_content = (
            getattr(crew.tasks[2].output, "raw", str(crew.tasks[2].output))
            if crew.tasks[2].output else "Plan generation failed."
        )

    return TripResponse(
        city_report=CityReportOutput(
            destinations=request.destinations,
            attractions_and_activities=city_report_content,
            recommendations="Generated by City Local Guide Expert",
        ),
        travel_plan=TravelPlanOutput(
            overall_plan="Generated by Travel Planning Expert",
            daily_itinerary=travel_plan_content,
        ),
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8002)
